services:
  - type: worker
    name: my-background-worker
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python3 worker.py"
    autoDeploy: true
